Executable              = $cmsRun
Universe                = vanilla
Getenv                  = True
Arguments               = config_cfg.py True $nJobs $(Process) $dataset $label

Output                  = condor_$(Process).out
Error                   = condor_$(Process).err
Log                     = condor_$(Process).log

+IsLocalJob             = true
Rank                    = TARGET.IsLocalSlot

Queue $nJobs
