#!/usr/bin/env bash

# Usage:
# $ checkJobs condor/MyCondorDir

DIR=$1

LOGS=`find ${DIR} -type f -regex ".*\/condor_[^/]*\.log$"`
TOTAL_ARR=($LOGS)
TOTAL=${#TOTAL_ARR[@]}

EXECUTED=0
DONE=0
PASS=0
if [ $TOTAL -ne 0 ]
then
  EXECUTED_LOGS=`grep -Hc "Job executing on host" ${LOGS} | grep -v ":0$" | sed "s/\(.*\):[^:]*$/\1/g"`
  EXECUTED_ARR=($EXECUTED_LOGS)
  EXECUTED=${#EXECUTED_ARR[@]}

  if [ $EXECUTED -ne 0 ]
  then
    DONE_LOGS=`grep -Hc "return value\|signal" ${EXECUTED_LOGS} | grep -v ":0$" | sed "s/\(.*\):[^:]*$/\1/g"`
    DONE_ARR=($DONE_LOGS)
    DONE=${#DONE_ARR[@]}
    if [ $DONE -ne 0 ]
    then
      PASS_LOGS=`grep -Hc "return value 0" ${DONE_LOGS} | grep -v ":0$" | sed "s/\(.*\):[^:]*$/\1/g"`
      PASS_ARR=($PASS_LOGS)
      PASS=${#PASS_ARR[@]}
    fi

    REMOVED_LOGS=`grep -Hc "SYSTEM_PERIODIC_REMOVE" ${EXECUTED_LOGS} | grep -v ":0$" | sed "s/\(.*\):[^:]*$/\1/g"`
    REMOVED_ARR=($REMOVED_LOGS)
    REMOVED=${#REMOVED_ARR[@]}
  fi
fi
FAIL=`echo "${DONE} ${PASS} - p" | dc`
RUNNING=`echo "${EXECUTED} ${PASS} - ${FAIL} - ${REMOVED} - p" | dc`
QUEUED=`echo "${TOTAL} ${EXECUTED} - p" | dc`

PASSFRAC=`echo "2 k ${PASS} 100 * ${TOTAL} / p" | dc`
FAILFRAC=`echo "2 k ${FAIL} 100 * ${TOTAL} / p" | dc`
REMOVEDFRAC=`echo "2 k ${REMOVED} 100 * ${TOTAL} / p" | dc`
RUNNINGFRAC=`echo "2 k ${RUNNING} 100 * ${TOTAL} / p" | dc`
QUEUEDFRAC=`echo "2 k ${QUEUED} 100 * ${TOTAL} / p" | dc`

echo "${PASS} / ${TOTAL} jobs have finished successfully (${PASSFRAC}%)."
echo "${FAIL} / ${TOTAL} jobs have failed (${FAILFRAC}%)."
echo "${REMOVED} / ${TOTAL} jobs have been removed due to resource usage (${REMOVEDFRAC}%)."
echo "${RUNNING} / ${TOTAL} jobs are running (${RUNNINGFRAC}%)."
echo "${QUEUED} / ${TOTAL} jobs are queued (${QUEUEDFRAC}%)."
